### PR TITLE
EmojiOne 4.5 Update

### PR DESCRIPTION
**Pull request by fiestacasey**
Emoji one released [version 4.5](https://www.emojione.com/emoji/v4) on Jan 23rd, 2019. This is all of the updated emojis.

### CODE REVIEW

**Comment by C404** [comment]
Thx @fiestacasey 🙌 
@hidakatsuya do you plan to merge this PR any time soon ? 🙏

**Comment by hidakatsuya** [comment]
Thank you for your contribution!!

However, I do not know that EmojiOne 4.5 can be used with OSS. It seems that the license of EmojiOne 4.5 does not specify it.
https://www.emojione.com/licenses

**Comment by fiestacasey** [comment]
Oh dang that does seem correct. Any idea how that differed / was approached with EmojiOne 3.1? It seems that documentation was removed / altered.

https://emojipedia.org/emojione/3.1/
> Images from EmojiOne are available under various licenses, with a early releases being open source.

but this links to the same URL you referenced and the oldest version on archive.org also doesn't mention OSS usage:
web archive org_web_20171023012924_https___www emojione com_licenses

**Comment by hidakatsuya** [comment]
Yes, I think that probably EmojiOne v3 has the same issue. I think that [Noto Emoji](https://github.com/googlei18n/noto-emoji) or [Twemoji](https://github.com/twitter/twemoji) can be used instead.

**Comment by hidakatsuya** [comment]
I will use NotoEmoji instead of EmojiOne in the next version of prawn-emoji.

**Comment by hidakatsuya** [comment]
Close this PR because of the bellow:

> I will use NotoEmoji instead of EmojiOne in the next version of prawn-emoji.

I'm going to switch Emoji on the following roadmap:

1. Fix some types of Emoji are not drawn (v2.2 or v3.0)
  - See https://github.com/hidakatsuya/prawn-emoji/blob/master/test/pdf/emoji_rendering/expect.pdf
2. Switch to NotoEmoji (v3.0)

Thanks all!

**Comment by hidakatsuya** [comment]
@fiestacasey @C404 
Now v3.0 has been released. I belive that your problem will be solved by v3.0.
https://github.com/hidakatsuya/prawn-emoji/blob/master/CHANGELOG.md#300

Please try it if you'd like!

**Pull request closed without merging**
